fresh_shop/cart/urls.py
from django.urls import path

from cart import views

urlpatterns = [
    # 加入购物车
    path('add_cart/', views.add_cart, name='add_cart'),
    # 购物车数量刷新
    path('cart_num/', views.cart_num, name='cart_num'),
    # 打开购物车
    path('cart/', views.cart, name='cart'),
    # 购物车计算价格
    path('cart_price/', views.cart_price, name='cart_price'),
    # 修改购物车中数量/选择状态
    path('change_cart/', views.change_cart, name='change_cart'),
    # 删除购物车中物品
    path('del_goods/', views.del_goods, name='del_goods'),
    path('del_cart/<int:id>/', views.del_cart, name='del_cart'),
]

fresh_shop/fresh_shop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from fresh_shop.settings import MEDIA_URL, MEDIA_ROOT
from goods import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('goods/', include(('goods.urls', 'goods'), namespace='goods')),
    path('order/', include(('order.urls', 'order'), namespace='order')),
    path('user/', include(('user.urls', 'user'), namespace='user')),
    # 首页路径
    path('', views.index),
]

urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

fresh_shop/goods/urls.py
from django.urls import path

from goods import views

urlpatterns = [
    # 首页
    path('index/', views.index, name='index'),
    # 详情
    path('detail/<int:id>/', views.detail, name='detail'),
    # 商品列表
    path('goods_list/<int:id>/', views.goods_list, name='goods_list'),
    # 查询商品
    path('search/', views.search, name='search'),
]

fresh_shop/order/urls.py
from django.urls import path

from order import views

urlpatterns = [
    # 结算功能
    path('place_order/', views.place_order, name='place_order'),
    # 创建订单
    path('order/', views.order, name='order'),
]

fresh_shop/user/urls.py
from django.urls import path

from user import views

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    # 个人中心
    path('user_center_info/', views.user_center_info, name='user_center_info'),
    # 我的订单
    path('user_center_order/', views.user_center_order, name='user_center_order'),
    # 收货地址
    path('user_center_site/', views.user_center_site, name='user_center_site'),
    # 浏览记录
    # path('user_cookies/', views.user_cookies, name='user_cookies'),
]

fresh_shop/cart/models.py
from django.db import models

from goods.models import Goods
from user.models import User


class ShoppingCart(models.Model):
    """
    购物车
    """
    user = models.ForeignKey(User, verbose_name='用户', on_delete=models.CASCADE)
    goods = models.ForeignKey(Goods, verbose_name='商品', on_delete=models.CASCADE)
    nums = models.IntegerField(default=0, verbose_name='数量')
    add_time = models.DateTimeField(auto_now_add=True, verbose_name='添加时间')
    is_select = models.BooleanField(default=True)

    class Meta:
        db_table = 'f_shopping_cart'

fresh_shop/cart/views.py
from django.http import JsonResponse
from django.shortcuts import render

from cart.models import ShoppingCart
from goods.models import Goods


def add_cart(request):
    if request.method == 'POST':
        # 接收商品id和商品数量num
        # 组装存储的商品格式：[goods_id, num, is_select]
        # 组装多个商品格式：[[goods_id, num, is_select],[goods_id, num, is_select],[goods_id, num, is_select]..]
        goods_id = int(request.POST.get('goods_id'))
        goods_num = int(request.POST.get('goods_num'))
        goods_list = [goods_id, goods_num, 1]

        session_goods = request.session.get('goods')
        if session_goods:
            # 1.添加重复的商品则修改
            flag = True
            for se_goods in session_goods:
                if se_goods[0] == goods_id:
                    se_goods[1] += goods_num
                    flag = False
            if flag:
                # 2.添加的商品不存在于购物车中，则新增
                session_goods.append(goods_list)
            request.session['goods'] = session_goods
            count = len(session_goods)
        else:
            # 第一次添加购物车，需组装购物车中商品格式为[[goods_id, num, is_select],[goods_id, num, is_select],..]
            # 向session中存数据
            request.session['goods'] = [goods_list]
            count = 1
        return JsonResponse({'code': 200, 'msg': '请求成功', 'count': count})


def cart_num(request):
    if request.method == 'GET':
        session_goods = request.session.get('goods')
        count = len(session_goods) if session_goods else 0
        return JsonResponse({'code': 200, 'msg': '请求成功', 'count': count})


def cart(request):
    if request.method == 'GET':
        session_goods = request.session.get('goods')
        # 组装返回格式：[objects1,objects2...]
        # objects==> [Goods Object, num, is_select, total_price]
        try:
            result = []
            for se_goods in session_goods:
                # se_goods为[goods_id, num, is_select]
                goods = Goods.objects.filter(pk=se_goods[0]).first()
                total_price = goods.shop_price * se_goods[1]
                data = [goods, se_goods[1], se_goods[2], total_price]
                result.append(data)
            return render(request, 'cart.html', {'result': result})
        except:
            msg = '购物车内暂时没有商品，登录后将显示您之前加入的商品'
            return render(request, 'cart.html', {'msg': msg})


def cart_price(request):
    if request.method == 'GET':
        session_goods = request.session.get('goods')
        # 总商品件数
        all_total = len(session_goods) if session_goods else 0
        all_price = 0
        is_select_num = 0
        for se_goods in session_goods:
            # se_goods为[goods_id, num, is_select]
            if se_goods[2]:
                goods = Goods.objects.filter(pk=se_goods[0]).first()
                all_price += goods.shop_price * se_goods[1]
                is_select_num += 1
        return JsonResponse({'code': 200, 'msg': '请求成功', 'all_total': all_total, 'all_price': all_price, 'is_select_num': is_select_num})


def change_cart(request):
    if request.method == 'POST':
        # 修改商品数量和选择状态
        # 其实就是修改session中商品信息，结构为[goods_id, num, is_select]

        # 1.获取商品id值和数量（或选择状态）
        goods_id = int(request.POST.get('goods_id'))
        goods_num = request.POST.get('goods_num')
        goods_select = request.POST.get('goods_select')
        # 修改
        session_goods = request.session.get('goods')
        for se_goods in session_goods:
            if se_goods[0] == goods_id:
                se_goods[1] = int(goods_num) if goods_num else se_goods[1]
                # se_goods[2] = int(goods_select) if goods_select else se_goods[2]
                se_goods[2] = int(goods_select)
                # break
        request.session['goods'] = session_goods
        return JsonResponse({'code': 200, 'msg': '请求成功'})


def del_goods(request):
    if request.method == 'POST':
        goods_id = int(request.POST.get('goods_id'))
        session_goods = request.session.get('goods')
        for index in range(len(session_goods)):
            if session_goods[index][0] == goods_id:
                session_goods.pop(index)
                break
        request.session['goods'] = session_goods
        return JsonResponse({'code': 200, 'msg': '请求成功'})


def del_cart(request, id):
    if request.method == 'POST':
        # 思路：通过传入的id值，去session中查找到删除的数据
        session_goods = request.session.get('goods')
        for se_goods in session_goods:
            # se_goods为[goods_id, num, is_select]
            if se_goods[0] == id:
                session_goods.remove(se_goods)
                break
        request.session['goods'] = session_goods
        # 删除数据库中购物车中已删除的商品
        user_id = request.session.get('user_id')
        if user_id:
            ShoppingCart.objects.filter(goods_id=id, user_id=user_id).delete()
        return JsonResponse({'code': 200, 'msg': '请求成功'})

fresh_shop/templates/base-main.html
{% extends 'base.html' %}

{% block css %}
{#    {% load static %}#}
{#    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">#}
    <link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
{% endblock %}

{% block js1 %}
    <script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
{% endblock %}


{% block header %}
    <div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				<div class="login_info fl" {% if user.id %} style="display:block;"{% endif %}>
					欢迎您：<em>{{ user.username }}</em>
                <span>|</span>
                <a href="{% url 'user:logout' %}">退出</a>
				</div>
				<div class="login_btn fl" {% if user.id %} style="display:none;"{% endif %}>
{#                    {% if user %}#}
{#                        <p style="display: inline-block;color: red;">{{ user.username }},欢迎登录！</p><a href="{% url 'user:logout' %}">退出</a>#}
{#                    {% else %}#}
                    <a href="{% url 'user:login' %}">登录</a>
{#                    {% endif %}#}
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user_center_info' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'cart:cart' %}">我的购物车</a>
					<span>|</span>
					<a href="/user/user_center_order/">我的订单</a>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

{% block search %}
    <div class="search_bar clearfix">
		<a href="/goods/index/" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="请输入商品全称">
			<input type="button" class="input_btn fr" name="" value="搜索" onclick="my_search()">
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'cart:cart' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">1</div>
		</div>
	</div>
    {% csrf_token %}
    <script>
        $.get('/cart/cart_num/',function (data) {
            if(data.code == '200'){
                $('#show_count').text(data.count)
            }
        })
        function my_search() {
            if (!$('.input_text').val()){
                {#$('.input_text').attr('placeholder', '请输入内容')#}
                alert('搜索内容不能为空')
            }else {
                var csrf = $('input[name="csrfmiddlewaretoken"]').val();
                var name = $('.input_text').val()
                {#$('.input_text').attr('placeholder', '请输入商品全称')#}
                $.ajax({
                    url: '/goods/search/',
                    type: 'POST',
                    data: {'name': name},
                    headers:{'X-CSRFToken': csrf},
                    dataType: 'json',
                    success: function (data) {
                        if (data.search_goods){
                            {#goods_search(data.search_goods)#}
                            self.location.href='/goods/detail/'+ data.search_goods +'/'
                        }else {
                            alert(data.msg)
                        }
                    },
                    error: function (data) {
                        
                    }
                })
            }
        }
    </script>
{% endblock %}

{% block footer %}
    <div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
{% endblock %}

fresh_shop/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    {% block css %}
    {% endblock %}

    {% block js1 %}
    {% endblock %}
</head>
<body>
    {% block header %}
    {% endblock %}

    {% block search %}
    {% endblock %}

    {% block content %}
    {% endblock %}

    {% block footer %}
    {% endblock %}

    {% block js2 %}
    {% endblock %}
</body>
</html>

fresh_shop/templates/cart.html
{% extends 'base-main.html' %}

{% block title %}
	天天生鲜-购物车
{% endblock %}

{#{% block search %}#}
{#	<div class="search_bar clearfix">#}
{#		<a href="/goods/index/" class="logo fl"><img src="/static/images/logo.png"></a>#}
{#		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;购物车</div>#}
{#		<div class="search_con fr">#}
{#			<input type="text" class="input_text fl" name="" placeholder="搜索商品">#}
{#			<input type="button" class="input_btn fr" name="" value="搜索">#}
{#		</div>		#}
{#	</div>#}
{#{% endblock %}#}

{% block content %}
    {% if not msg %}
        <div class="total_count">全部商品<em>2</em>件</div>
        <ul class="cart_list_th clearfix">
            <li class="col01">商品名称</li>
            <li class="col02">商品单位</li>
            <li class="col03">商品价格</li>
            <li class="col04">数量</li>
            <li class="col05">小计</li>
            <li class="col06">操作</li>
        </ul>
        {% for goods in result %}
        <ul class="cart_list_td clearfix" id="g_{{ good.0.id }}">
            <li class="col01"><input type="checkbox" name="" onclick="change_chioce({{ goods.0.id }})" id="checkbox_{{ goods.0.id }}" {% if goods.2 %} checked="checked" {% endif %}></li>
            <li class="col02"><img src="/media/{{ goods.0.goods_front_image }}"></li>
            <li class="col03">{{ goods.0.name }}<br><em>{{ goods.0.shop_price }}元/500g</em></li>
            <li class="col04">500g</li>
            <li class="col05" id="d_{{ goods.0.id }}">{{ goods.0.shop_price }}元</li>
            <li class="col06">
                <div class="num_add">
                    <a href="javascript:;" class="add fl" onclick="add_cart({{ goods.0.id }})">+</a>
                    <input type="text" class="num_show fl" id="num_show_{{ goods.0.id }}" value="{{ goods.1 }}">
                    <a href="javascript:;" class="minus fl" onclick="sub_cart({{ goods.0.id }})">-</a>
                </div>
            </li>
            <li class="col07 " id="t_{{ goods.0.id }}">{{ goods.3 }}元</li>
    {#		<li class="col08"><a href="javascript:;" onclick="del_goods({{ goods.0.id }})">删除</a></li>#}
            <li class="col08"><a href="javascript:;" onclick="del_cart({{ goods.0.id }})">删除</a></li>
        </ul>
        {% endfor %}
    {% csrf_token %}
    <script>
        function change_chioce(id) {
            if ($('#checkbox_'+id).attr("checked")){
                $('#checkbox_'+id).removeAttr("checked")
                change_cart(id, $('#num_show_'+id).val(), 0)
                {#不能在这更新会经过中间件，调用后才更新#}
                {#cart_price()#}
            }else{
                $('#checkbox_'+id).attr("checked", "checked")
                change_cart(id,$('#num_show_'+id).val(), 1)
                {#cart_price()#}
            }
        }
        var csrf = $('input[name="csrfmiddlewaretoken"]').val()
        function del_cart(id) {
            $.ajax({
                url: '/cart/del_cart/' + id + '/',
                type: 'POST',
                headers: {'X-CSRFToken': csrf},
                dataType: 'json',
                success: function (data) {
                     {#刷新数量/总价/件数#}
                    {#刷新页面#}
                    location.reload()
                    {#$('#g_'+id).remove();#}
                     {#cart_price()#}
                },
                error: function () {
                    alert('删除失败')
                }
            })
        }
        {#function del_goods(id) {#}
        {#    $('#g_'+id).remove();#}
        {#    $.ajax({#}
        {#        url: '/cart/del_goods/',#}
        {#        type: 'POST',#}
        {#        data: {'goods_id': id},#}
        {#        headers: {'X-CSRFToken': csrf},#}
        {#        dataType: 'json',#}
        {#        success: function (data) {#}
                     {#刷新数量/总价/件数#}
        {#            location.reload()#}
        {#             cart_price()#}
        {#        },#}
        {#        error: function () {#}
        {#        }#}
        {#    })#}
        {#\}#}
    </script>
{#	<ul class="cart_list_td clearfix">#}
{#		<li class="col01"><input type="checkbox" name="" checked></li>#}
{#		<li class="col02"><img src="images/goods/goods003.jpg"></li>#}
{#		<li class="col03">大兴大棚草莓<br><em>16.80元/500g</em></li>#}
{#		<li class="col04">500g</li>#}
{#		<li class="col05">16.80元</li>#}
{#		<li class="col06">#}
{#			<div class="num_add">#}
{#				<a href="javascript:;" class="add fl">+</a>#}
{#				<input type="text" class="num_show fl" value="1">	#}
{#				<a href="javascript:;" class="minus fl">-</a>	#}
{#			</div>#}
{#		</li>#}
{#		<li class="col07">16.80元</li>#}
{#		<li class="col08"><a href="javascript:;">删除</a></li>#}
{#	</ul>#}
	

	<ul class="settlements">
		<li class="col01"><input type="checkbox" name="" checked=""></li>
		<li class="col02">全选</li>
		<li class="col03">合计(不含运费)：<span>¥</span><em>42.60</em><br>共计<b>2</b>件商品</li>
		<li class="col04"><a href="{% url 'order:place_order' %}">去结算</a></li>
	</ul>
    {% else %}
        <div style="margin-left: 800px;margin-top: 300px;margin-bottom: 300px;color: red;font-size: 30px;">
            <div>{{ msg }}</div>
            <div style="width: 50%;text-align: center;">
                <button style="display: inline-block;"><a href="/user/login/">登录</a></button><a href="/goods/index/">去购物</a>
            </div>
        </div>
    {% endif %}
    {% csrf_token %}
    <script>
{#        刷新价格/简述#}
        function cart_price() {
            $.get('/cart/cart_price/', function (data) {
            if(data.code == '200'){
                $('.total_count em').html(data.all_total);
                $('.settlements .col03 em').html(data.all_price);
                $('.settlements .col03 b').html(data.is_select_num)
            }
        })
        }
        cart_price()
        {#添加商品数量#}
        function add_cart(id) {
            var num = $('#num_show_' + id).val()
            var new_num = parseInt(num) + 1
            $('#t_'+id).html(String((new_num * parseInt($('#d_'+id).text())))+ '元')
            $('#num_show_' + id).val(new_num)
            if ($('#checkbox_'+id).attr("checked")){
                change_cart(id, new_num)
            }
        }
        {#减少商品数量#}
        function sub_cart(id) {
            var num = $('#num_show_' + id).val()
            if(parseInt(num)>1){
                var new_num = parseInt(num) - 1
                $('#num_show_' + id).val(new_num)
                $('#t_'+id).html(String((new_num * parseInt($('#d_'+id).text())))+ '元')
                if ($('#checkbox_'+id).attr("checked")){
                    change_cart(id, new_num)
                }
            }
        }
    {#    修改数量或选择状态#}
        var csrf = $('input[name="csrfmiddlewaretoken"]').val()
        function change_cart(id, new_num, goods_select=1) {
            $.ajax({
                url: '/cart/change_cart/',
                type: 'POST',
                data: {'goods_id': id, 'goods_num': new_num, 'goods_select': goods_select},
                headers: {'X-CSRFToken': csrf},
                dataType: 'json',
                success: function (data) {
                     {#刷新数量/总价/件数#}
                    console.log(data)
                     cart_price()
                },
                error: function () {

                }
            })
        }
    </script>
{% endblock %}

{% block js2 %}
{% endblock %}

fresh_shop/templates/index.html
{% extends 'base-main.html' %}

{% block title %}
	天天生鲜-首页
{% endblock %}

{% block js1 %}
    {{ block.super }}
	<script type="text/javascript" src="/static/js/jquery-ui.min.js"></script>
	<script type="text/javascript" src="/static/js/slide.js"></script>
{% endblock %}

{% block content %}
	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
            {% for dt in result %}
{#			    <li><a href="#model01" class="fruit">#}
			    <li><a href="{% url 'goods:goods_list' dt.0.id %}">
                    {% for type in category_type %}
                        {% if type.0 == dt.0.category_type %}
                            {{ type.1 }}
                    {% endif %}
                {% endfor %}
                </a></li>
            {% endfor %}
{#			<li><a href="#model02" class="seafood">海鲜水产</a></li>#}
{#			<li><a href="#model03" class="meet">猪牛羊肉</a></li>#}
{#			<li><a href="#model04" class="egg">禽类蛋品</a></li>#}
{#			<li><a href="#model05" class="vegetables">新鲜蔬菜</a></li>#}
{#			<li><a href="#model06" class="ice">速冻食品</a></li>#}
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
				<li><img src="/static/images/slide.jpg" alt="幻灯片"></li>
				<li><img src="/static/images/slide02.jpg" alt="幻灯片"></li>
				<li><img src="/static/images/slide03.jpg" alt="幻灯片"></li>
				<li><img src="/static/images/slide04.jpg" alt="幻灯片"></li>
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
			<a href="#"><img src="/static/images/adv01.jpg"></a>
			<a href="#"><img src="/static/images/adv02.jpg"></a>
		</div>
	</div>

{% for data in result %}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model02">
                {% for type in category_type %}
                    {% if type.0 == data.0.category_type %}
                        {{ type.1 }}
                    {% endif %}
                {% endfor %}
            </h3>
{#			<div class="subtitle fl">#}
{#				<span>|</span>#}
{#				<a href="#">河虾</a>#}
{#				<a href="#">扇贝</a>#}
{#			</div>#}

{#            console.log({{ data.0.id }})#}
			<a href="{% url 'goods:goods_list' data.0.id %}" class="goods_more fr">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/media/{{ data.0.category_front_image }}"></div>

			<ul class="goods_list fl">
                {% for goods in data.1 %}
				<li>
					<h4><a href="{% url 'goods:detail' goods.id %}">{{ goods.name }}</a></h4>
					<a href="{% url 'goods:detail' goods.id %}"><img src="/media/{{ goods.goods_front_image }}"></a>
					<div class="prize">¥ {{ goods.shop_price }}</div>
{#                    <button onclick="make_mark({{ goods.id }})">2132132131</button>#}
				</li>
                {% endfor %}
			</ul>
		</div>
	</div>
{% endfor %}
{#    <script>#}
{#        var csrf = $('input[name="csrfmiddlewaretoken"]').val()#}
{#        function make_mark(id) {#}
{#            $.ajax({#}
{#                url: 'user:user_cookies',#}
{#                type: 'POST',#}
{#                data: {'goods_id':id},#}
{#                headers: {'X-CSRFToken': csrf},#}
{#                dataType: 'json',#}
{#                success: function (data) {#}
{##}
{#                },#}
{#                error: function (data) {#}
{##}
{#                }#}
{#            })#}
{#        }#}
{#    </script>#}
{% endblock %}

{% block js2 %}
	<script type="text/javascript" src="/static/js/slideshow.js"></script>
	<script type="text/javascript">
		BCSlideshow('focuspic');
		var oFruit = document.getElementById('fruit_more');
		var oShownum = document.getElementById('show_count');

		var hasorder = localStorage.getItem('order_finish');

		if(hasorder)
		{
			oShownum.innerHTML = '2';
		}

		oFruit.onclick = function(){
			window.location.href = 'list.html';
		}
	</script>
{% endblock %}

fresh_shop/templates/login.html
{% extends 'base-main.html' %}

{% block title %}
	天天生鲜-登录
{% endblock %}

{% block header %}
{% endblock %}

{% block search %}
{% endblock %}

{% block content %}
    <div class="login_top clearfix">
		<a href="/goods/index/" class="login_logo"><img src="/static/images/logo02.png"></a>
	</div>
	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="{% url 'user:register' %}">立即注册</a>
				</div>
				<div class="form_input">
					<form action="" method="post">
                        {% csrf_token %}
						<input type="text" name="username" class="name_input" placeholder="请输入用户名">
						<div class="user_error" style="display: block;">{{ errors.username }}</div>
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error" style="display: block;">{{ errors.pwd }}</div>
{#						<div class="more_input clearfix">#}
{#							<input type="checkbox" name="">#}
{#							<label>记住用户名</label>#}
{#							<a href="#">忘记密码</a>#}
{#						</div>#}
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>
{% endblock %}